### ISSUE TITLE
Integration with it:test instead of test

### ISSUE THREAD

**Issue by agile-jordi** [skipoleschris/xsbt-cucumber-plugin#14]
I'd like to know if is there any way to integrate the cucumber execution with the [it:test](https://github.com/harrah/xsbt/wiki/Testing) instead of the test configuration, since I'd like to keep the test config just for unit tests, so that they run fast (as my BDD tests are quite much slower than the average unit test).

Thanks again!

**Comment by agile-jordi** [comment]
I was able to work-arround that one using [Additional test configurations with shared sources](https://github.com/harrah/xsbt/wiki/Testing). So I can live without that it:test integration I was trying to get.

Thanks again.

**Comment by skipoleschris** [comment]
It should be fairly easy to do this as I already did the work to add to the test:test phase. I see it's not urgent, but I'll try to take a look as it's probably useful to other people as well. Thanks for the suggestion,

**Comment by skipoleschris** [comment]
I managed to get this to work successfully. You can now add cucumber as a test framework into the IntegrationTest config. There's description in the README and an example project in the testProjects directory sowing this working.

Fixed in 0.7.1

**Comment by agile-jordi** [comment]
Great! Thanks!
