### ISSUE TITLE
Test projects (testProject, testIntegrationProject and multiModuleTestProject) fail to build: sbt-cucumber-integration not found

### ISSUE THREAD

**Issue by agile-jordi** [skipoleschris/xsbt-cucumber-plugin#15]
Hello again,

I've been using xsbt-cucumber-plugin for some days, but due to my adventures with an unestable Scala version, I had published the plugin locally to my repo. And everything was going fine.

But I set up a CI environment and got this error when trying to build my project:

(*:update) sbt.ResolveException: download failed: templemore#sbt-cucumber-integration_2.9.2;0.7.0!sbt-cucumber-integration_2.9.2.jar

So I tried to remove that particular project from my workstation local repository and the failure repeated when building my project.

So I tried the 3 test projects in the xsbt-cucumber-plugin repo and they fail as well.

I'm using sbt 0.12.

Doing publish-local of the plugin itself solves the issue... so there may be an issue with the repository.

Thanks again for the plugin and for taking your time helping with this. I'm really sorry to have to bother you again.

**Comment by agile-jordi** [comment]
I found out that adding the repo resolver to the build.sbt (not the plugins build.sbt but the project build.sbt) is needed to avoid the issue. I just added:

resolvers += "Templemore Repository" at "http://templemore.co.uk/repo"

Maybe cucumberSeetings should do this automatically?

**Comment by skipoleschris** [comment]
Thanks. I'll look into this an make sure the the plugin adds the dependency. I'll try to put out a new release this evening to fix it.

**Comment by skipoleschris** [comment]
This should now be fixed. When adding the cucumber settings to a project this now also adds the templemore repository as a resolver.

Fixed in 0.7.1

**Comment by agile-jordi** [comment]
Version 0.7.1 works perfectly. Thanks again!
