### ISSUE TITLE
Html Report does not format the Feature elements on new lines

### ISSUE THREAD

**Issue by randomcoder** [skipoleschris/xsbt-cucumber-plugin#17]
When generating the Html report from the `cucumber` task the Feature descriptions are all displayed on a single line

```
In order to do something interesting As an interested person I want to be able to push a button
```

Ideally this would be formatted either on three lines or as an unordered list

```
In order to do something interesting
As an interested person
I want to be able to push a button
```

or
- In order to do something interesting
- As an interested person
- I want to be able to push a button"

This seems to be caused by the use of `\n` in the _report.js_ to indicate a new line which firefox and chrome seem to ignore.

**Comment by skipoleschris** [comment]
Looks like this is fixed now. Not anything that the plugin does as all the html report output comes from cucumber.
