### ISSUE TITLE
scala 2.10.0

### ISSUE THREAD

**Issue by nicl** [skipoleschris/xsbt-cucumber-plugin#23]
Hi, 

I've added the following into my build file:

resolvers += "Templemore Repository" at "http://templemore.co.uk/repo",

...and...

"templemore" % "sbt-cucumber-plugin" % "0.7.2" (under my dependencies)

But the plugin isn't found. I've looked at your repo and it doesn't look like you support 2.10 yet.

Are you planning on updating this soon? Is there anything I can do to help?

**Comment by skipoleschris** [comment]
Hi,
It should work fine for Scala 2.10.0 when running under SBT 0.12.x. I'm running locally with this configuration. There are binaries in the repo for this configuration (http://templemore.co.uk/repo/templemore/sbt-cucumber-plugin_2.10_0.12/0.7.2/).

If you can zip up a template project and email it over (chris at templemore dot co dot uk) I'll give it a try and see if I can diagnose any problems.

**Comment by skipoleschris** [comment]
Hi,
Just gave this another test locally and it works fine. Take a look at the testProjects/testProject2_10 in the repository as this has a working setup for using Scala 2.10. If you can't run that project for some reason then let me know. Just tested it locally using:

Scala 2.10.0
ST 0.12.2

**Comment by nicl** [comment]
Hey thanks. Just tried out the example project and it works great, so I must have something wrong with my project setup. I'll have a look to find out what's different.

Thanks.
