### ISSUE TITLE
Running tests by name not working

### ISSUE THREAD

**Issue by zvozin** [skipoleschris/xsbt-cucumber-plugin#3]
cucumber "Something"  
[info] Installing any missing Gems...
[info] Running cucumber...
[error] invalid option: --names (OptionParser::InvalidOption)
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1451:in `complete'
[error] org/jruby/RubyKernel.java:1191:in`catch'
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1449:in `complete'
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1262:in`parse_in_order'
[error] org/jruby/RubyKernel.java:1191:in `catch'
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1255:in`parse_in_order'
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1249:in `order!'
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1340:in`permute!'
[error] file:/Users/azuzin/.ivy2/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/1.8/optparse.rb:1361:in `parse!'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/lib/cucumber/cli/options.rb:103:in`parse!'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/lib/cucumber/cli/configuration.rb:25:in `parse!'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/lib/cucumber/cli/main.rb:54:in`configuration'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/lib/cucumber/cli/main.rb:62:in `run_drb_client'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/lib/cucumber/cli/main.rb:34:in`execute!'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/lib/cucumber/cli/main.rb:20:in `execute'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/bin/cucumber:14:in`(root)'
[error] org/jruby/RubyKernel.java:1063:in `load'
[error] /Users/azuzin/.jruby/gems/gems/cucumber-1.0.0/bin/cucumber:4:in`(root)'
[error] org/jruby/RubyKernel.java:1063:in `load'
[error] /Users/azuzin/.jruby/gems/bin/cuke4duke:19:in`(root)'
[success] Total time: 8 s, completed 9/14/11 12:01 PM

**Comment by skipoleschris** [comment]
Thanks for spotting this and for the pull request. All merged. I'll post a new bug fix release later today.

**Comment by zvozin** [comment]
No worries, glad to help.
Any chance at all you could bump a minor version and deploy to the repo?
I'm running everyone in my org on a local copy - it'd be lovely to switch
them back to mainstream.

## Thanks a million again!

On Fri, Sep 16, 2011 at 9:44 AM, Chris Turner <
reply@reply.github.com>wrote:

> Thanks for spotting this and for the pull request. All merged. I'll post a
> new bug fix release later today.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/skipoleschris/xsbt-cucumber-plugin/issues/3#issuecomment-2116442

## 

"If you can't conceal it seamlessly, expose it vigorously"

**Comment by skipoleschris** [comment]
Hi,
I've pushed a 0.3 release to my repository.

I'm currently keeping a close eye on cucumber-jvm and I hope to switch to this from the ruby implementation as soon as it looks stable.

Regards,
Chris

**Comment by zvozin** [comment]
Yeap, picked up - thanks again!
Cucumber-jvm would be de-lovely - jRuby is kind of a pain.
- z

On Fri, Sep 16, 2011 at 11:53 AM, Chris Turner <
reply@reply.github.com>wrote:

> Hi,
> I've pushed a 0.3 release to my repository.
> 
> I'm currently keeping a close eye on cucumber-jvm and I hope to switch to
> this from the ruby implementation as soon as it looks stable.
> 
> Regards,
> Chris
> 
> On 16 Sep 2011, at 19:24, zvozin wrote:
> 
> > No worries, glad to help.
> > Any chance at all you could bump a minor version and deploy to the repo?
> > I'm running everyone in my org on a local copy - it'd be lovely to switch
> > them back to mainstream.
> > 
> > ## Thanks a million again!
> > 
> > On Fri, Sep 16, 2011 at 9:44 AM, Chris Turner <
> > reply@reply.github.com>wrote:
> > 
> > > Thanks for spotting this and for the pull request. All merged. I'll post
> > > a
> > > new bug fix release later today.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > 
> > > https://github.com/skipoleschris/xsbt-cucumber-plugin/issues/3#issuecomment-2116442
> > 
> > ## 
> > 
> > "If you can't conceal it seamlessly, expose it vigorously"
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/skipoleschris/xsbt-cucumber-plugin/issues/3#issuecomment-2117389
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/skipoleschris/xsbt-cucumber-plugin/issues/3#issuecomment-2117648

## 

"If you can't conceal it seamlessly, expose it vigorously"
