### ISSUE TITLE
Upgrade to last cucumber-jvm version

### ISSUE THREAD

**Issue by mguillermin** [skipoleschris/xsbt-cucumber-plugin#31]
It would be nice if the plugin could be upgraded to the last stable version of cucumber-jvm (1.1.4 at the time of writing). 

I don't know if it implies big changes in the plugin code but some interesting issues have been fixed in cucumber-jvm (like the use of DataTable arguments : (https://github.com/cucumber/cucumber-jvm/issues/443)

Thanks for your work on this plugin.

**Comment by dkowis** [comment]
It seems that this has already been updated, but I can't find where to get the snapshot version downloaded from :(

**Comment by skipoleschris** [comment]
Hi,
I've merged in all the pull requests and I'm just fixing a couple of other bits at the same time. Hoping to complete this and push a release sometime tomorrow  (paid work permitting). 

Chris Turner

**Comment by mguillermin** [comment]
That's a good news !
Thank you @skipoleschris

**Comment by skipoleschris** [comment]
Version 0.8.0 is now available that uses version 1.1.4 of cucumber jam
