### ISSUE TITLE
Repository down

### ISSUE THREAD

**Issue by charltonaustin** [skipoleschris/xsbt-cucumber-plugin#39]
It appears that http://templemore.co.uk/repo is down? Should we really be using this or some other repository?

**Comment by skipoleschris** [comment]
Hi. Sorry about that I had a catastrophic server failure today. While I get it all sorted out (or work out how to publish to a more global repository) I've pushed the binaries up on to github. I've updated the README with the changes, but basically there's two changes that need to be made:

1) project/plugins.sbt:
Change the url to the Templemore Repository to: https://raw.github.com/skipoleschris/xsbt-cucumber-plugin/mvn-repo

2) build.sbt or project/Build.scala:
Add the Templemore Repository as a resolver:
    resolvers += "Templemore Repository" at "https://raw.github.com/skipoleschris/xsbt-cucumber-plugin/mvn-repo"

I'm working on getting my server back up and running as a priority. Once everything is back to normal I'll try publishing to oss.sonatype.org

Sorry for the inconvenience.

**Comment by charltonaustin** [comment]
No worries. Thanks for the help. I hope everything works out well. :D

On Tue, Apr 22, 2014 at 11:51 AM, Chris Turner notifications@github.comwrote:

> Hi. Sorry about that I had a catastrophic server failure today. While I
> get it all sorted out (or work out how to publish to a more global
> repository) I've pushed the binaries up on to github. I've updated the
> README with the changes, but basically there's two changes that need to be
> made:
> 
> 1) project/plugins.sbt:
> Change the url to the Templemore Repository to:
> https://raw.github.com/skipoleschris/xsbt-cucumber-plugin/mvn-repo
> 
> 2) build.sbt or project/Build.scala:
> Add the Templemore Repository as a resolver:
> resolvers += "Templemore Repository" at "
> https://raw.github.com/skipoleschris/xsbt-cucumber-plugin/mvn-repo"
> 
> I'm working on getting my server back up and running as a priority. Once
> everything is back to normal I'll try publishing to oss.sonatype.org
> 
> Sorry for the inconvenience.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/skipoleschris/xsbt-cucumber-plugin/issues/39#issuecomment-41079090
> .

## 

Respectfully,
Charlton Austin

**Comment by skipoleschris** [comment]
Repository back up and running. You can put the settings back to the way they were again.
